version: "3.9"
services:
  php:
    build: .
    healthcheck:
     test: ["CMD-SHELL", "curl -sS http://nginx | grep -c works > /dev/null"]
     interval: 5s
     timeout: 5s
     retries: 5
    volumes:
      - type: bind
        source: ./www
        target: /var/www


  web:
    image: nginx:latest
    volumes:
      - type: bind
        source: ./nginx
        target: /etc/nginx/conf.d
      - type: bind
        source: ./www
        target: /var/www
    ports:
      - "80:80"
